name: Build Hasura Binary
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make musl-dev curl

      - name: Setup Haskell (GHC & Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.6'

      - name: Install Haskell Dependencies
        run: |
          cabal update
          cabal install --only-dependencies

      - name: Build Hasura
        run: |
          make build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasura-binary
          path: bin/hasura
