name: Build Hasura Binary

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Extract Tag Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set CURRENT_VERSION
        run: echo "$VERSION" > server/CURRENT_VERSION

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make musl-dev curl unixodbc-dev

      - name: Setup Haskell (GHC & Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.12'

      - name: Cache Cabal Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
            server/dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install Haskell Dependencies
        run: |
          cabal update
          cabal build all --only-dependencies

      - name: Build GraphQL Engine
        run: cabal build exe:graphql-engine

      - name: Copy README.md to server/
        run: cp README.md server/

      - name: Build Executable Binary
        run: |
          mkdir -p artifacts
          cabal install exe:graphql-engine --installdir=artifacts
          mv artifacts/graphql-engine artifacts/graphql-engine-$VERSION

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphql-engine
          path: artifacts/graphql-engine-*

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Tag Version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download Built Binary
        uses: actions/download-artifact@v4
        with:
          name: graphql-engine
          path: artifacts/

      - name: List Downloaded Artifacts
        run: ls -l artifacts/

      - name: Rename and Make Binary Executable
        run: |
          mv artifacts/graphql-engine-* artifacts/graphql-engine
          chmod +x artifacts/graphql-engine

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          VERSION: ${{ github.ref_name }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/graphql-engine:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/graphql-engine:${{ env.VERSION }}
