name: Build Hasura Binary

on:
  push:
    branches: [ "**" ]
#  pull_request:
#    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set CURRENT_VERSION
        run: echo "12345" > server/CURRENT_VERSION

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc make musl-dev curl unixodbc-dev

      - name: Setup Haskell (GHC & Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.12'

      - name: Cache Cabal Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
            server/dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update Cabal Version
        run: |
          ghcup install cabal 3.12
          ghcup set cabal 3.12
          cabal --version

      - name: Install Haskell Dependencies
        run: |
          cabal update
          cabal build all --only-dependencies

      - name: Build GraphQL Engine
        run: |
          cabal build exe:graphql-engine

      - name: Copy README.md to server/
        run: cp README.md server/

      - name: Build executable binary
        run: |
          cabal install exe:graphql-engine --installdir=/tmp/.cabal/bin

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphql-engine-binary
          path: /tmp/.cabal/bin/graphql-engine

