name: Build Hasura Binary

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        include:
          - os: ubuntu-latest
            target: "linux"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set CURRENT_VERSION
        run: echo "12345" > server/CURRENT_VERSION

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y gcc make musl-dev curl unixodbc-dev

      - name: Setup Haskell (GHC & Cabal)
        uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.12'

      - name: Cache Cabal Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
            server/dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Install Haskell Dependencies
        run: |
          cabal update
          cabal build all --only-dependencies

      - name: Build GraphQL Engine
        run: cabal build exe:graphql-engine

      - name: Copy README.md to server/
        run: cp README.md server/

      - name: Build executable binary
        run: |
          mkdir -p artifacts
          cabal install exe:graphql-engine --installdir=artifacts

      - name: Rename binary for platform
        run: |
          mv artifacts/graphql-engine artifacts/graphql-engine-${{ matrix.target }} || mv artifacts/graphql-engine.exe artifacts/graphql-engine-${{ matrix.target }}.exe
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: graphql-engine-${{ matrix.target }}
          path: artifacts/graphql-engine*

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Binary
        uses: actions/download-artifact@v4
        with:
          name: graphql-engine-linux
          path: artifacts/

      - name: Make Binary Executable
        run: chmod +x artifacts/graphql-engine-linux

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: server
          file: server/Dockerfile
          push: true
          tags: ${{ github.repository_owner }}/graphql-engine:latest

